#!/bin/bash
# if CCACHE_DISABLE=1 g++ tiles.c -o tiles.app --std=c++20 -lsqlite3 -Werror -Wfatal-errors; then
if CCACHE_DISABLE=1 g++ tiles.cpp -o tiles.app --std=c++20 -lsqlite3 -Werror -Wfatal-errors; then
	./tiles.app
else
	echo "Compilation failed. Unable to execute ./tiles.app."
fi